spring:
  application:
    name: springinitializr-mcp
  main:
    banner-mode: "off"
  ai:
    mcp:
      server:
        name: springinitializr
        version: 1.0.0

logging:
  level:
    root: off